language: go

go:
  - 1.6

sudo: false

install:
  - go get github.com/Masterminds/glide
  
script:
  - cd $TRAVIS_BUILD_DIR
  - export GOPATH=$GOPATH:`pwd`
  - export PATH=$PATH:`pwd`/bin
  - make
  - make test
